image: node:13.12.0

definitions:
  services:
    docker:
      memory: 3000

pipelines:
  branches:
    develop:
      - step:
          name: Test
          caches:
            - node
          script:
            - npm install
            - npm rebuild
            - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
            - npm run e2e -- --protractor-config=e2e/protractor.conf.js
      - step:
          name: Build
          size: 2x
          script:
            - export IMAGE_NAME=$DOCKER_HUB_USERNAME/$APPLICATION_NAME:$BITBUCKET_COMMIT
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME
          services:
            - docker
      - step:
          name: Deploy
          deployment: staging
          script:
            - sed -i "s|{{image}}|$DOCKER_HUB_USERNAME/$APPLICATION_NAME:$BITBUCKET_COMMIT|g" deployment.yaml
            - pipe: atlassian/kubectl-run:1.1.6
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: 'deployment.yaml'
                KUBECTL_ARGS:
                  - '--namespace=real-estate'
