apiVersion: v1
kind: Namespace
metadata:
  name: real-estate

---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: real-estate
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImRteGhaSGx6YkdGMmNtOXRZVzVsYm10dk9rUjBjMTloY2pkemRIbHNaVGM9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy44IChkYXJ3aW4pIgoJfSwKCSJleHBlcmltZW50YWwiOiAiZGlzYWJsZWQiLAoJInN0YWNrT3JjaGVzdHJhdG9yIjogInN3YXJtIgp9Cg==
type: kubernetes.io/dockerconfigjson

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: re-dashboard
    app.kubernetes.io/instance: real-estate
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: real-estate
    app.kubernetes.io/managed-by: docker
    environment: staging
    tier: frontend
    partition: outright-digital
  name: re-dashboard
  namespace: real-estate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: re-dashboard
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: re-dashboard
    spec:
      containers:
        - image: {{image}}
          imagePullPolicy: "Always"
          name: re-dashboard
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: re-dashboard
    app.kubernetes.io/instance: real-estate
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: real-estate
    app.kubernetes.io/managed-by: docker
    environment: staging
    tier: frontend
    partition: outright-digital
  name: re-dashboard
  namespace: real-estate
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: re-dashboard
status:
  loadBalancer: {}

---

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-re-dashboard-prod
  namespace: cert-manager
  labels:
    environment: production
    tier: certificate
    app.kubernetes.io/part-of: real-estate
    partition: outright-digital
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vlad@outright.digital
    privateKeySecretRef:
      name: letsencrypt-re-dashboard-prod
    solvers:
      - http01:
          ingress:
            class: nginx

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: re-dashboard-ingress
  namespace: real-estate
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-re-dashboard-prod
  labels:
    environment: staging
    tier: ingress
    partition: outright-digital
spec:
  tls:
    - hosts:
        - re-dashboard.outright.xyz
      secretName: re-dashboard-tls
  rules:
    - host: re-dashboard.outright.xyz
      http:
        paths:
          - backend:
              serviceName: re-dashboard
              servicePort: 80
